apply plugin: 'com.android.library'



android {
    compileSdkVersion 29
    defaultConfig {
        minSdkVersion 17
        targetSdkVersion 33
        versionCode 1100
        versionName "1.1.0.0"
        consumerProguardFiles 'consumer-rules.pro'
        testInstrumentationRunner 'androidx.test.runner.AndroidJUnitRunner'

    }
    buildTypes {
        release {
            buildConfigField("long", "VERSION_CODE", "${defaultConfig.versionCode}")
            buildConfigField("String","VERSION_NAME","\"${defaultConfig.versionName}\"")
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }

        debug {
            buildConfigField("long", "VERSION_CODE", "${defaultConfig.versionCode}")
            buildConfigField("String","VERSION_NAME","\"${defaultConfig.versionName}\"")
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
        beta.initWith(release)
        beta {

        }
    }
    lintOptions {
        abortOnError false
    }
    libraryVariants.all { variant ->
        variant.outputs.each { output ->
            output.outputFileName = "by_sdk_${defaultConfig.versionName}_${variant.buildType.name}.aar"
        }
    }
    repositories {
        flatDir {
            dirs 'libs'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {

    implementation 'androidx.appcompat:appcompat:1.0.0'
    compileOnly(name: 'open_ad_sdk_7.3.0.7', ext: 'aar') // 穿山甲
    compileOnly(name: 'GDTSDK.unionNormal.4.662.1532', ext: 'aar') // 广点通
    compileOnly(name: 'Baidu_MobAds_SDK-release_v9.422', ext: 'aar') // 百度
    compileOnly(name: 'ks_adsdk-ad-4.11.30.1-publishRelease', ext: 'aar') // 快手

}